DROP TABLE IF EXISTS T_CERTIFICADO;
DROP TABLE IF EXISTS T_VAGA;
DROP TABLE IF EXISTS T_LOG_AUDITORIA;
DROP TABLE IF EXISTS T_USUARIOS;
DROP TABLE IF EXISTS T_EMPRESA;
DROP TABLE IF EXISTS T_CURSO;
GO

CREATE TABLE T_USUARIOS (
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL_USUARIO VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    CADASTRO DATE DEFAULT GETDATE(),
    CPF VARCHAR(14) NOT NULL,
    CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL_USUARIO),
    CONSTRAINT UK_CPF_USUARIO UNIQUE (CPF)
);
GO

CREATE TABLE T_EMPRESA (
    ID_EMPRESA INT IDENTITY(1,1) PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(150) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    EMAIL_EMPRESA VARCHAR(100) NOT NULL,
    CONSTRAINT UKC_EMP_CNPJ UNIQUE (CNPJ)
);
GO

CREATE TABLE T_CURSO (
    ID_CURSO INT IDENTITY(1,1) PRIMARY KEY,
    NOME_CURSO VARCHAR(150) NOT NULL,
    DESCRICAO VARCHAR(MAX) NULL,
    QT_HORAS INT NOT NULL
);
GO

CREATE TABLE T_VAGA (
    ID_VAGA INT IDENTITY(1,1) PRIMARY KEY,
    ID_EMPRESA INT NOT NULL,
    NOME_VAGA VARCHAR(100) NOT NULL,
    DESCRICAO_VAGA VARCHAR(MAX) NULL,
    SALARIO DECIMAL(10, 2) NULL,
    DT_PUBLICACAO DATE DEFAULT GETDATE(), 
    CONSTRAINT FK_VAGA_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES T_EMPRESA(ID_EMPRESA)
);
GO

CREATE TABLE T_CERTIFICADO (
    ID_CERTIFICADO INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_CURSO INT NOT NULL,
    DT_EMISSAO DATE NOT NULL,
    DESCRICAO VARCHAR(200) NULL,
    CODIGO_VALIDACAO VARCHAR(50) NOT NULL,
    CONSTRAINT UK_CERT_VALIDACAO UNIQUE (CODIGO_VALIDACAO),
    CONSTRAINT FK_CERT_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIOS(ID_USUARIO),
    CONSTRAINT FK_CERT_CURSO FOREIGN KEY (ID_CURSO) REFERENCES T_CURSO(ID_CURSO)
);
GO

CREATE TABLE T_LOG_AUDITORIA (
    ID_LOG INT IDENTITY(1,1) PRIMARY KEY,
    NOME_TABELA VARCHAR(50) NOT NULL,
    DS_OPERACAO CHAR(1) NOT NULL,
    DATA_OPERACAO DATE DEFAULT GETDATE(),
    NM_USUARIO_DB VARCHAR(100) NOT NULL
);
GO

PRINT 'Tabelas do EcoLesson criadas com sucesso no Azure SQL!';